<?xml version="1.0" encoding="utf-8"?><Database Name="CountryDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TBVM3;Initial Catalog=CountryDB;Integrated Security=True" SettingsObjectName="Country.Properties.Settings" SettingsPropertyName="CountryDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BigCity" Member="BigCity">
    <Type Name="BigCity">
      <Column Name="CityId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Budget" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="City_BigCity" Member="City" ThisKey="CityId" OtherKey="CityId" Type="City" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Capital" Member="Capital">
    <Type Name="Capital">
      <Column Name="CityId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mayor" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Area" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="City_Capital" Member="City" ThisKey="CityId" OtherKey="CityId" Type="City" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="City">
    <Type Name="City">
      <Column Name="CityId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CountPeople" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="City_BigCity" Member="BigCity" ThisKey="CityId" OtherKey="CityId" Type="BigCity" Cardinality="One" />
      <Association Name="City_Capital" Member="Capital" ThisKey="CityId" OtherKey="CityId" Type="Capital" Cardinality="One" />
      <Association Name="Country_City" Member="Country" ThisKey="CountryId" OtherKey="CountryId" Type="Country" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Country">
    <Type Name="Country">
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Area" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Country_City" Member="City" ThisKey="CountryId" OtherKey="CountryId" Type="City" />
    </Type>
  </Table>
</Database>